# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csAgwad9ItYQaOW2Usrr_R496Z153qq1
"""

import re
import pandas as pd
from datetime import datetime

# Map nama bulan Indonesia & Inggris
MONTHS = {
    "januari": 1, "jan": 1, "january": 1,
    "februari": 2, "feb": 2, "february": 2,
    "maret": 3, "mar": 3, "march": 3,
    "april": 4, "apr": 4,
    "mei": 5, "may": 5,
    "juni": 6, "jun": 6, "june": 6,
    "juli": 7, "jul": 7, "july": 7,
    "agustus": 8, "agu": 8, "aug": 8, "august": 8,
    "september": 9, "sep": 9, "sept": 9,
    "oktober": 10, "okt": 10, "oct": 10,
    "november": 11, "nov": 11,
    "desember": 12, "des": 12, "dec": 12
}

def normalize_year(y):
    """Konversi tahun menjadi 4 digit"""
    y = y.replace("'", "")
    if len(y) == 2:
        return 2000 + int(y)
    return int(y)

def parse_date(text):
    """Ekstrak tanggal dari teks Keterangan"""

    text_low = text.lower()

    # Pola: YEAR, DAY MONTH  → contoh: "2024, 17 desember"
    pattern1 = r"(\d{4})\s*,\s*(\d{1,2})\s+([a-zA-Z]+)"
    m = re.search(pattern1, text_low)
    if m:
        year = int(m.group(1))
        day = int(m.group(2))
        month = MONTHS.get(m.group(3)[:3], None)
        if month:
            return f"{day:02d}-{month:02d}-{year}"

    # Pola: DAY MONTH YEAR  → contoh: "17 desember 2024" atau "7 aug '24"
    pattern2 = r"(\d{1,2})\s+([a-zA-Z]+)\s+'?(\d{2,4})"
    m = re.search(pattern2, text_low)
    if m:
        day = int(m.group(1))
        month = MONTHS.get(m.group(2)[:3], None)
        year = normalize_year(m.group(3))
        if month:
            return f"{day:02d}-{month:02d}-{year}"

    # Jika tidak cocok pola apa pun
    return None

def process_excel(input_path="transaksi-raw-partial.xlsx",
                  output_path="transaksi-output.xlsx"):

    # Baca Excel sheet transaksi
    df = pd.read_excel(input_path, sheet_name="transaksi")

    # Buat kolom tanggal hasil ekstraksi
    df["Tanggal Transaksi"] = df["Keterangan"].apply(
        lambda x: parse_date(str(x))
    )

    # Simpan ke file Excel tanpa index
    df.to_excel(output_path, sheet_name="transaksi", index=False)